framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
#                    - validation
                    - doctrine_transaction
            query.bus: ~
            event.bus: ~
        failure_transport: failed
        transports:
            sync:
                dsn: 'sync://'
            doctrine:
                dsn: 'doctrine://default'
                options:
                    queue_name: event_store
            failed:
                dsn: 'doctrine://default'
                options:
                    queue_name: event_failed
        routing:
            App\Application\SyncMessageInterface:
                - sync
                - doctrine
            App\Application\AsyncMessageInterface: doctrine
