version: "3.7"
services:
  fpm:
    image: clever/symfony/php7.4-fpm-alpine:latest
    build:
      context: .
      args:
        PHP_VERSION: 7.4-fpm-alpine
        COMPOSER_VERSION: latest
    command: php -v
