version: "3.7"
services:
  workspace:
    build:
      context: .
      target: symfony_dev
      args:
        PHP_VERSION: 7.4-fpm-alpine
        COMPOSER_VERSION: latest
    command: php -v
    volumes:
      - ./:/app
      - ./docker/workspace/.zshrc:/root/.zshrc


