version: "3.7"
services:
  fpm:
    build:
      context: .
      target: symfony_dev
      args:
        PHP_VERSION: 7.4-fpm-alpine
        COMPOSER_VERSION: latest
    volumes:
      - ./:/app
      - ./docker/workspace/.zshrc:/root/.zshrc
  nginx:
    image: nginx
