version: "3.7"
services:
  fpm:
    image: clever/symfony/php7.4-fpm-alpine:dev
    build:
      context: .
      target: symfony_dev
      args:
        PHP_VERSION: 7.4-fpm-alpine
        COMPOSER_VERSION: latest
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./docker/workspace/.zshrc:/root/.zshrc
      - app_data:/app

  mariadb:
    image: mariadb:10.4.11-bionic
    environment:
      MYSQL_ROOT_PASSWORD: sf
      MYSQL_DATABASE: sf
      MYSQL_USER: sf
      MYSQL_PASSWORD: sf
    volumes:
      - /var/lib/mysql

  nginx:
    image: nginx:1.16-alpine
    depends_on:
      - fpm
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - app_data:/app
    ports:
      - 8080:80

volumes:
  app_data:
    driver: local
