App\Domain\Review\Review:
  group_sequence:
  constraints: ~
  properties:
    score:
      - NotBlank: ~
      - NotNull: ~
      - PositiveOrZero: ~
      - LessThanOrEqual:
          value: 100

App\Domain\Offer\Offer:
  group_sequence: ~
  constraints:
#    - App\Infrastructure\Constraint\OfferNameIsUnique: ~
    - App\Infrastructure\Constraint\OfferUuidIsUnique: ~
  properties: ~
