kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "sf4.fullname" . }}-sf4-configmap
  labels:
    {{- include "sf4.labels" . | nindent 4 }}
data:
  env: {{ .Values.fpm.env }}
  debug: {{ .Values.fpm.debug }}
  verbosity: {{ .Values.fpm.verbosity }}
