#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello:
  path: /hello/{id}
  controller: App\UI\Controller\Hello

show:
  path: /
  controller: App\UI\Controller\Show

offer_create:
  path: /offer/create
  controller: App\UI\Controller\Offer\Create

offer_increment_version:
  path: /offer/{uuid}/incrementVersion/{version}
  controller: App\UI\Controller\Offer\IncrementVersion
